const list = [
  {
    id: 98951,
    name: 'Ashutosh ',
    first_name: 'Ashutosh',
    last_name: '',
    email: 'ashutosh@xto10x.com',
    initials: 'As',
    designation: null,
    department_id: null,
    department_name: '',
    sub_department_id: null,
    sub_department_name: '',
    city: null,
    profile_image_url: null,
    manager_name: '',
    manager_id: null,
    matrix_manager_id: null,
    org_tree: '98951',
    has_child: false,
    has_active_child: false,
    has_parent: false,
    has_sibling: true,
    status: 1,
    gender: null,
    level: 'None',
    role: {
      id: 29,
      name: 'Admin'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: null,
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'eae34335-4563-4209-b5b4-ad087226865e',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98869,
    name: 'Dee 001',
    first_name: 'Dee',
    last_name: '001',
    email: 'deekshav0001@gmail.com',
    initials: 'D0',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c',
      medium:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c',
      thumbnail:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c'
    },
    manager_name: 'Dee 2',
    manager_id: 98871,
    matrix_manager_id: null,
    org_tree: '98871.98869',
    has_child: true,
    has_active_child: true,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'fc6e35a5-6be4-4d95-8226-65ba4e1d9c9c',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98859,
    name: 'Dee 017',
    first_name: 'Dee',
    last_name: '017',
    email: 'deekshav017@gmail.com',
    initials: 'D0',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c',
      medium:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c',
      thumbnail:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c'
    },
    manager_name: 'Deeksha ',
    manager_id: 98858,
    matrix_manager_id: null,
    org_tree: '98871.98858.98859',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'c422022f-ef7b-4645-b589-b9d23fc3eaea',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98870,
    name: 'Dee 2',
    first_name: 'Dee',
    last_name: '2',
    email: 'deeksha+1@xto10x.com',
    initials: 'D2',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF',
      medium:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF',
      thumbnail:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF'
    },
    manager_name: 'Deeksha ',
    manager_id: 98858,
    matrix_manager_id: null,
    org_tree: '98871.98858.98870',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'feedbe31-643d-4732-b469-3fe73229d25d',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98871,
    name: 'Dee 2',
    first_name: 'Dee',
    last_name: '2',
    email: 'deeksha+2@xto10x.com',
    initials: 'D2',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: null,
    manager_name: '',
    manager_id: null,
    matrix_manager_id: null,
    org_tree: '98871',
    has_child: true,
    has_active_child: true,
    has_parent: false,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'b94ea954-dce9-4c87-b1a3-ed99f3d333d9',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98872,
    name: 'Dee 3',
    first_name: 'Dee',
    last_name: '3',
    email: 'deeksha+3@xto10x.com',
    initials: 'D3',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: null,
    manager_name: 'Dee 001',
    manager_id: 98869,
    matrix_manager_id: null,
    org_tree: '98871.98869.98872',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: false,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: '1d1ca9ed-a26c-4741-8a84-248f36481837',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  {
    id: 98858,
    name: 'Deeksha ',
    first_name: 'Deeksha',
    last_name: '',
    email: 'deeksha@xto10x.com',
    initials: 'De',
    designation: null,
    department_id: null,
    department_name: '',
    sub_department_id: null,
    sub_department_name: '',
    city: null,
    profile_image_url: {
      large:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx',
      medium:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx',
      thumbnail:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx'
    },
    manager_name: 'Dee 2',
    manager_id: 98871,
    matrix_manager_id: null,
    org_tree: '98871.98858',
    has_child: true,
    has_active_child: true,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: null,
    level: 'None',
    role: {
      id: 29,
      name: 'Admin'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: null,
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'Deeksha',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  }
];

export default list;

export const userListMap = {
  '98858': {
    id: 98858,
    name: 'Deeksha ',
    first_name: 'Deeksha',
    last_name: '',
    email: 'deeksha@xto10x.com',
    initials: 'De',
    designation: null,
    department_id: null,
    department_name: '',
    sub_department_id: null,
    sub_department_name: '',
    city: null,
    profile_image_url: {
      large:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx',
      medium:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx',
      thumbnail:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/9bf81252-9751-4c13-b220-5c096583a473?iuk=xqwHaoCLx'
    },
    manager_name: 'Dee 2',
    manager_id: 98871,
    matrix_manager_id: null,
    org_tree: '98871.98858',
    has_child: true,
    has_active_child: true,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: null,
    level: 'None',
    role: {
      id: 29,
      name: 'Admin'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: null,
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'Deeksha',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98859': {
    id: 98859,
    name: 'Dee 017',
    first_name: 'Dee',
    last_name: '017',
    email: 'deekshav017@gmail.com',
    initials: 'D0',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c',
      medium:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c',
      thumbnail:
        'https://lh3.googleusercontent.com/a-/AOh14GjZqNaxmPg5jvRJBt4UvlDyKhILxzAiV2Yltq9fRQ=s96-c'
    },
    manager_name: 'Deeksha ',
    manager_id: 98858,
    matrix_manager_id: null,
    org_tree: '98871.98858.98859',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'c422022f-ef7b-4645-b589-b9d23fc3eaea',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98869': {
    id: 98869,
    name: 'Dee 001',
    first_name: 'Dee',
    last_name: '001',
    email: 'deekshav0001@gmail.com',
    initials: 'D0',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c',
      medium:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c',
      thumbnail:
        'https://lh3.googleusercontent.com/a-/AOh14GgMcZA0P3GFvHiufAo6Sr0t2FmY_ymR3ieiFxzBig=s96-c'
    },
    manager_name: 'Dee 2',
    manager_id: 98871,
    matrix_manager_id: null,
    org_tree: '98871.98869',
    has_child: true,
    has_active_child: true,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'fc6e35a5-6be4-4d95-8226-65ba4e1d9c9c',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98870': {
    id: 98870,
    name: 'Dee 2',
    first_name: 'Dee',
    last_name: '2',
    email: 'deeksha+1@xto10x.com',
    initials: 'D2',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: {
      large:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF',
      medium:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF',
      thumbnail:
        'https://xto10x-store.s3.ap-south-1.amazonaws.com/defbde5a-3352-432b-ac33-dbf5301db42a?iuk=qKn4O21UF'
    },
    manager_name: 'Deeksha ',
    manager_id: 98858,
    matrix_manager_id: null,
    org_tree: '98871.98858.98870',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'feedbe31-643d-4732-b469-3fe73229d25d',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98871': {
    id: 98871,
    name: 'Dee 2',
    first_name: 'Dee',
    last_name: '2',
    email: 'deeksha+2@xto10x.com',
    initials: 'D2',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: null,
    manager_name: '',
    manager_id: null,
    matrix_manager_id: null,
    org_tree: '98871',
    has_child: true,
    has_active_child: true,
    has_parent: false,
    has_sibling: true,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'b94ea954-dce9-4c87-b1a3-ed99f3d333d9',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98872': {
    id: 98872,
    name: 'Dee 3',
    first_name: 'Dee',
    last_name: '3',
    email: 'deeksha+3@xto10x.com',
    initials: 'D3',
    designation: '',
    department_id: 8607,
    department_name: '',
    sub_department_id: 8608,
    sub_department_name: '',
    city: '',
    profile_image_url: null,
    manager_name: 'Dee 001',
    manager_id: 98869,
    matrix_manager_id: null,
    org_tree: '98871.98869.98872',
    has_child: false,
    has_active_child: false,
    has_parent: true,
    has_sibling: false,
    status: 1,
    gender: '',
    level: '',
    role: {
      id: 30,
      name: 'Employee'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: '',
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: '1d1ca9ed-a26c-4741-8a84-248f36481837',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  },
  '98951': {
    id: 98951,
    name: 'Ashutosh ',
    first_name: 'Ashutosh',
    last_name: '',
    email: 'ashutosh@xto10x.com',
    initials: 'As',
    designation: null,
    department_id: null,
    department_name: '',
    sub_department_id: null,
    sub_department_name: '',
    city: null,
    profile_image_url: null,
    manager_name: '',
    manager_id: null,
    matrix_manager_id: null,
    org_tree: '98951',
    has_child: false,
    has_active_child: false,
    has_parent: false,
    has_sibling: true,
    status: 1,
    gender: null,
    level: 'None',
    role: {
      id: 29,
      name: 'Admin'
    },
    org_roles: null,
    reports_to: null,
    reportees: null,
    employee_id: null,
    doj: null,
    added_from: 'dockabl_upload',
    updated_from: null,
    reference_id: 'eae34335-4563-4209-b5b4-ad087226865e',
    active_modules: ['objectives', 'feedbacks', 'reviews'],
    role_id: null
  }
};

export const disabledUsersMap = {
  98859: {
    reason: 'This user is disabled'
  }
};
